server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:
  application:
    name: partner-service

  config:
    import:
      - optional:file:.env[.properties]

  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${PARTNER_DB_URL}
    username: ${PARTNER_DB_USERNAME}
    password: ${PARTNER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
